baseURL = '/'
languageCode = 'en-us'
title = 'Klovnstation 14'

[module]
  [[module.imports]]
    path = "github.com/willfaught/paige"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.scss]
    generate = false
  [markup.highlight]
    noclasses = false
    style = "github"

[params.paige]
  description = "Klovnstation 14 Design Documents"

[paige.site]
  color = "#ec1c24"
  color_scheme = "auto"
  disable_menu = false
